// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo.exe -godefs -- -I C:/npcap-sdk-1.01/Include generate_defs.go

package main

type timeval struct {
	Sec	int32
	Usec	int32
}
type pcapPktHdr struct {
	Ts	timeval
	Caplen	uint32
	Len	uint32
}
type bytePtr *uint8

const pcapErrorNotActivated = -0x3
